- hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: httpd
        state: present
    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes